name = "notes-kinokonoko-io"
compatibility_date = "2025-05-08"
main = "./dist/_worker.js/index.js"

[[routes]]
pattern = "notes.kinokonoko.io/*"
zone_id = "29e34a162ec1b3866014aa906c6e4677"

[assets]
directory = "./dist"

[observability]
enabled = true